[package]
name = "heroicons-leptos"
description = "Leptos port of Heroicons."
homepage = "https://heroicons.rustforweb.org/frameworks/leptos.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
# leptos.workspace = true
